# Create AWS infrastructure
---
- hosts: "localhost"
  connection: "local"
  gather_facts: false

  vars:
    region: eu-west-1
    image: ami-04c58523038d79132 # Ubuntu 18.04 LTS

  tasks:
    - name: Provisioning an EC2 instance and a security group
      block:
        - name: Upload public key to AWS
          ec2_key:
            name: "ansible-webserver"
            key_material: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
            region: "{{ region }}"
            aws_access_key: "{{ec2_access_key}}"
            aws_secret_key: "{{ec2_secret_key}}"

        - name: Create a security group
          ec2_group:
            name: "webserver-security-group"
            description: "Security group for Webserver"
            region: "{{ region }}"
            aws_access_key: "{{ec2_access_key}}"
            aws_secret_key: "{{ec2_secret_key}}"
            rules:
              - proto: tcp
                ports:
                  - 22
                cidr_ip: 0.0.0.0/0
                rule_desc: allow all on ssh port
              - proto: tcp
                ports:
                  - 80
                cidr_ip: 0.0.0.0/0
                rule_desc: allow all on HTTP port
            rules_egress:
              - proto: "all"
                cidr_ip: "0.0.0.0/0"
          register: security_group

        - name: Provision an EC2 instance
          ec2:
            aws_access_key: "{{ec2_access_key}}"
            aws_secret_key: "{{ec2_secret_key}}"
            key_name: "ansible-webserver"
            id: "ansible-webserver-5"
            group_id: "{{ security_group.group_id }}"
            image: "{{ image }}"
            instance_type: t2.micro
            region: "{{ region }}"
            wait: true
            count: 1
          register: webserver

        - name: Tag the webserver EC2 instance
          ec2_tag:
            aws_access_key: "{{ec2_access_key}}"
            aws_secret_key: "{{ec2_secret_key}}"
            region: "{{ region }}"
            resource: "{{ webserver.instances[0].id }}"
            state: present
            tags:
              Name: Webserver

        - name: Tag the Security group
          ec2_tag:
            aws_access_key: "{{ec2_access_key}}"
            aws_secret_key: "{{ec2_secret_key}}"
            region: "{{ region }}"
            resource: "{{ security_group.group_id }}"
            state: present
            tags:
              Name: Webserver          
