---
- hosts: tag_Name_Webserver
  user: ubuntu
  become: yes
  name: Install webserver items

  tasks:
    - include: roles/webserver/tasks/apache.yml
  #- include: roles/webserver/tasks/helloworld.yml

