---
- hosts: all

  gather_facts: no

  become: yes

  user: ubuntu

  vars:
    root_db_password: SecretRootPassword
    application_db_password: SecretAppPassword

  roles:
    - apache
    - php
    - mysql
    - deploy

  handlers:
    - name: Restart MySQL
      service:
        name: mysql
        state: restarted
