- name: Install mySQL
  vars:
    packages:
      - python3-pip
      - mysql-server
  apt:
    pkg: "{{ packages }}"
    update_cache: yes
    state: latest

- name: Install the Python PyMySQL module using Pip
  pip:
    name: pymysql

- name: Ensure mySQL is running and starts automatically
  service:
    name: mysql
    state: started
    enabled: yes
  become: yes

- name: Ensure mysql root password is updated for all root accounts
  mysql_user:
    user: root
    host: "{{ item }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    password: "{{ root_db_password }}"
    priv: "*.*:ALL,GRANT"
    check_implicit_admin: true
  loop: "{{ mysql.hosts }}"
  become: yes
  notify: Restart MySQL

- name: Create config file with root password credentials
  template:
    src: my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    mode: 0600
  become: yes
  notify: Restart MySQL

- name: Create a database called website
  mysql_db:
    name: website
    state: present
  register: database_created

- name: Create database user
  mysql_user:
    name: website_user
    password: "{{ application_db_password }}"
    priv: "*.*:ALL"
    state: present
  when: database_created.changed

- name: Copy our website.sql data file to import
  copy:
    src: website.sql
    dest: /home/ubuntu/website.sql
  when: database_created.changed

- name: Restore database
  mysql_db:
    name: website
    state: import
    target: /home/ubuntu/website.sql
    login_user: website_user
    login_password: "{{ application_db_password }}"
  when: database_created.changed

- name: Remove database file
  file:
    path: /home/ubuntu/website.sql
    state: absent
